version: '2.0'

services:

  web:
    container_name: "serveur-web"
    image: "nginx:latest"
    ports:
      - "8001:80"
    volumes:
      - web-file:/usr/share/nginx/html
    networks:
      - front-web
#################Redirection des logs ici
    logging:  
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:514"
#*********************************************************************************************************************************************************
  db:
    container_name: "serveur-db"
    image: "mysql:latest"
    ports:
      - "3306:3306"
    volumes:
      - db-file:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - back-web
#################Redirection des logs ici
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:514"
#******************************************************************************************************************************************************************
  ping:
    build: .
    networks:
      - front-web
      - back-web
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:514"

volumes:
  web-file: {}
  db-file: {}

networks:
  front-web:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24

  back-web:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.20.0/24



## On a utilisé 'syslog' On peut aussi utiliser gelf avec kibana pour les logs ou d'autres outils pour une visualisation interactive mais également d'autres outils