version: '2.0'
services:



  web:  # 1. Mon premier service
    container_name: "serveur-web"
    image: "nginx:latest"
    ports:
      - "8001:80"  # Liste pour les ports 
    volumes:
      - web-file:/usr/share/nginx/html:rw  # rw est pas nécessaire ici (lecture-écriture par défaut)
    networks:
      - "front-web"



  db:  # 2. Mon deuxième service
    container_name: "serveur-db"  
    image: "mysql:latest"  
    ports:
      - "3306:3306"  
    volumes:
      - db-file:/var/lib/mysql:rw  # rw est aussi optionnel ici
    environment:
      - MYSQL_ROOT_PASSWORD=root  # Définit le mot de passe du compte root pour MySQL
    networks:
      - "back-web"


  ping:
    build: .  
    networks: # On ajoute le prseau au ping pour qu'il pluisse comminquer avec les autres services
      - "front-web"
      - "back-web"


volumes:
  web-file: {}  #Création du volume pour web (ubuntu)
  db-file: {}   # Création du volume pour MySQL
networks:
  front-web: # Le réseau front-web
   driver: "bridge"
   ipam: # ça c'est le sous réseau
    config:
     - subnet : 172.20.20.0/24
  networks: #Le réseau back-web
  back-web:
   driver: "bridge"
   ipam: # ça c'est le sous réseau
    config:
     - subnet : 172.21.20.0/24

# On déclare un noveau back-web en bas réseau qui permet au service ping de commmuniquer avec les deux autres  services qui entre eux de communiquent pas car l'un etant dans le réeau front et l'autre dans le resaeu back.