version: '2.0'
services:
  web:
    # 1. Mon premier service
    container_name: "serveur-web"
    image: "nginx:latest"
    ports:
      - "8001:80" # Liste pour les ports (toujours avec des guillemets)
    volumes:
      - "./html:/usr/share/nginx/html" # Correction du chemin relatif (ajout de ./)
